### ISSUE TITLE
GPG key JUST expired

### ISSUE THREAD

**Issue by kokbent** [virtualstaticvoid/heroku-docker-r#20]
The Michael Rutter key for CRAN just expired on 2020-10-16. So whenever we pull the DockerHub image, and try to install packages it throws an error. Solution seems to be just rebuild the image and push (for my local machine I needed to remove and re-add the key and the new expiry date is 2027).

**Comment by virtualstaticvoid** [comment]
Thanks for this!

I've triggered a new [build](https://travis-ci.org/github/virtualstaticvoid/heroku-docker-r/builds/736594143) so that the new key is included in the docker images.

**Comment by virtualstaticvoid** [comment]
Unfortunately the build has failed due to an issue with the plumber package. I'll need to investigate further to resolve it, before releasing the new build.

**Comment by virtualstaticvoid** [comment]
The [build](https://travis-ci.org/github/virtualstaticvoid/heroku-docker-r/builds/736620693) is now fixed and updated Dockerhub images published.

**Comment by diegocl02** [comment]
Hi @virtualstaticvoid, we are still getting the error when trying to use the r-buildpack on one of our apps on Heroku. Do I need to do something in special to get the updated keys?

```
GPG error: https://cloud.r-project.org/bin/linux/ubuntu bionic-cran40/ InRelease: The following signatures were invalid: EXPKEYSIG 51716619E084DAB9 Michael Rutter <marutter@gmail.com>
```
